name: Test Action
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run action
        id: slack_release_notify
        uses: ./
        with:
          tag: 'v1.0'
          channel: 'C0651SH3K16'
          appName: 'cookme-releases'
          jiraBaseUrl: 'https://your-jira-instance.atlassian.net'
          jiraProjectKey: 'TICKET'
          repoOwner: ${{ github.repository_owner }}
          repoName: ${{ github.repository }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Check outputs
        run: |
          echo "Payload: ${{ steps.slack_release_notify.outputs.payload }}"